CREATE TABLE IF NOT EXISTS vendors (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  phone VARCHAR(30),
  notes TEXT,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stone_types (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS shapes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS settings (
  setting_key VARCHAR(64) PRIMARY KEY,
  setting_value VARCHAR(255) NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS gems (
  id INT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(50) NOT NULL UNIQUE,
  qr_token VARCHAR(64) NOT NULL UNIQUE,
  stone_type_id INT NOT NULL,
  weight DECIMAL(10,3) NOT NULL,
  shape_id INT NOT NULL,
  purchasing_price DECIMAL(12,2) NOT NULL,
  bought_from_vendor_id INT NOT NULL,
  current_vendor_id INT NULL,
  asking_price DECIMAL(12,2) NULL,
  status ENUM('IN_STOCK','WITH_VENDOR','SOLD','RETURNED') NOT NULL DEFAULT 'IN_STOCK',
  sold_price DECIMAL(12,2) NULL,
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (stone_type_id) REFERENCES stone_types(id),
  FOREIGN KEY (shape_id) REFERENCES shapes(id),
  FOREIGN KEY (bought_from_vendor_id) REFERENCES vendors(id),
  FOREIGN KEY (current_vendor_id) REFERENCES vendors(id)
);

CREATE TABLE IF NOT EXISTS custody_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  gem_id INT NOT NULL,
  action ENUM('CREATED','ASSIGNED','RETURNED','SOLD','REASSIGNED','UPDATED') NOT NULL,
  from_vendor_id INT NULL,
  to_vendor_id INT NULL,
  asking_price DECIMAL(12,2) NULL,
  sold_price DECIMAL(12,2) NULL,
  note VARCHAR(255),
  actor_phone VARCHAR(30),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (gem_id) REFERENCES gems(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS otps (
  id INT AUTO_INCREMENT PRIMARY KEY,
  phone VARCHAR(30) NOT NULL,
  code_hash VARCHAR(255) NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  consumed TINYINT(1) NOT NULL DEFAULT 0,
  attempts INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_phone (phone)
);
